# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift

before_install:
  - sudo gem install cocoapods

script:
  - pod install --repo-update --project-directory=Example/CoreData/
  - pod install --repo-update --project-directory=Example/Realm/
  - pod install --repo-update --project-directory=Example/RealmSwift/
  - set -o pipefail && xcodebuild test -workspace Example/CoreData/SyncKitCoreData.xcworkspace -scheme SyncKitCoreDataExample -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -workspace Example/Realm/SyncKitRealm.xcworkspace -scheme SyncKitRealmExample -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -workspace Example/RealmSwift/SyncKitRealmSwift.xcworkspace -scheme SyncKitRealmSwiftExample -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' ONLY_ACTIVE_ARCH=NO | xcpretty
#  - travis_wait 30 pod lib lint --allow-warnings
